'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("JeopardyArmyEdition.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Who can initiate a Bar to Reenlistment? 
        '''
        '''Any commander in the soldier’s chain of command 
        '''
        '''Who is the final approving authority for a Bar to Reenlistment? 
        '''
        '''A Commander who is one approval level higher than the commanding authority 
        '''
        '''Soldiers SGM and below who have not reenlisted under the indefinite reenlistment program are required to 
        '''receive Retention Interviews. When are they done? 
        '''
        '''
        '''Career Counselor: 30 days from arrival to unit 
        '''Unit Commander 90 days from arrival 
        '''Unit Commander 15-1 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Board_Study_Guide_new() As String
            Get
                Return ResourceManager.GetString("Board_Study_Guide_new", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property jeopardy_board_fill() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("jeopardy_board_fill", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property jeopardy_Daily_Double() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("jeopardy_Daily_Double", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property jeopardy_intro() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("jeopardy_intro", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property jeopardy_think() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("jeopardy_think", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Jeopardy_Times_up() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Jeopardy_Times_up", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property jeopardyARMY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jeopardyARMY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property jeopardyARMY1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("jeopardyARMY1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
